### ISSUE TITLE
RelicsOfCthonia bug

### ISSUE THREAD

**Issue by SrMonsterYT** [FN-FAL113/RelicsOfCthonia#11]
in version RelicsOfCthonia vDEV - 9 (git dfe76aba) is coming many items and is not working the percentage that was configured in version RelicsOfCthonia - DEV 8 (git a7ef6).jar did not have this problem

slimefun and addons version:  https://prnt.sc/h6efV-Smhnvu

it is happening that the addon is not checking the percentages and is dropping a lot of items

video: https://www.youtube.com/watch?v=i5-oVyWiNcc

**Comment by FN-FAL113** [comment]
will revert some of the previous randomization methods, appreciate it.

**Comment by FN-FAL113** [comment]
this is actually not a bug but how java generates random numbers are not well distributed since it uses same seed. I'll bring back the previous randomization method I used which adds biases to the final random number generation outcome.
