### ISSUE TITLE
World protection creates easily farmable relics.

### ISSUE THREAD

**Issue by EOT3000** [FN-FAL113/RelicsOfCthonia#12]
**Describe the bug**
Repearedly breaking natural netherrack in a protected area (world guard, factions, etc) will cause the plugin to drop many relics, because the block will not get removed after each break.

**To Reproduce (Important)**
Go to the nether. Create a world guard region that includes natural netherrack and have someone without permission to break it repeatedly break the block. This will not break the block due to protection, but will create many relics.

Fixable by changing this line to priority monitor: https://github.com/FN-FAL113/RelicsOfCthonia/blob/main/src/main/java/ne/fnfal113/relicsofcthonia/listeners/MiningListener.java#L29 .

**Comment by FN-FAL113** [comment]
Will be implemented, appreciate it.
