### ISSUE TITLE
Clearing "Condition" in lore

### ISSUE THREAD

**Issue by EpicPlayerA10** [FN-FAL113/RelicsOfCthonia#2]
**Describe the bug**
When you place a relic and break it then relic will be without condition

**To Reproduce (Important)**
1. Place a relic
2. Break a relic
3. In inventory will be shown `Condition: %`

**Expected behavior**
It should not clear condition

**Screenshots**
![image](https://user-images.githubusercontent.com/62206933/175779505-e45f66dd-5fe7-4d6c-a50f-6b645c918b57.png)

**Server Log**

**Environment (REQUIRED)**
```
This Server uses the following setup of Slimefun:
Paper git-Paper-386 (MC: 1.18.2)
Slimefun DEV - 1015 (git 2c4f886f)
Metrics-Module #28
Java 17
Installed Addons: (15)
Networks vDEV - 37 (git f1915513)
CrystamaeHistoria vDEV - 75 (git 12c8d18f)
RelicsOfCthonia vDEV - 2 (git 3f8ef79c)
SlimefunWarfare vDEV - 80 (git 364331cf)
ExoticGarden vDEV - 78 (git 7f9a5f63)
ShopChestDoughPatch v1.0-SNAPSHOT
InfinityExpansion vDEV - 140 (git 0098d2fb)
CMILib v1.2.0.3
SFCalc vDEV - 37 (git dfc0fc41)
SimpleUtils vDEV - 15 (git 4250fd5e)
SlimefunIdConverter v1.0.0
ExtraHeads vDEV - 23 (git 0b59a770)
Galactifun vDEV - 63 (git 364ecbf5)
FluffyMachines vDEV - 118 (git 23a6b1c4)
CMI v9.2.0.4
```

 - Server Software and Version (Spigot/Paper):
 - Minecraft version: 1.18.2
 - Slimefun version: DEV 1015
 - RelicsOfCthonia version: DEV 2

**Comment by FN-FAL113** [comment]
Will check this out

**Comment by FN-FAL113** [comment]
Any thoughts if I make relics unplaceable?
