### ISSUE TITLE
Nether World Name

### ISSUE THREAD

**Issue by xMikux** [FN-FAL113/RelicsOfCthonia#3]
**Describe the bug**
If nether world name not same as world_nether, then the relic won't drop on mob kill and block break

**To Reproduce (Important)**
1. Open server.properties, change level-name name.
2. Open the server to see result.

**Expected behavior**
Can have config to setting nether world name.

**Screenshots**

**Server Log**

**Environment (REQUIRED)**
![image](https://user-images.githubusercontent.com/26039249/175815780-2766e3da-1ef2-4099-962a-6b2729a05e4c.png)

**Comment by FN-FAL113** [comment]
new update now uses world environment instead of the hardcoded world name
